name:           Programmer Tips
highlighter:    pygments

source:         .
destination:    ../output
markdown:       kramdown
markdown_ext:   'markdown,mkdown,mkdn,mkd,md'
exclude:        ['README.md', 'node_modules', '*.less']
url:            http://programer.tips

paginate:       5
#paginate:      5
paginate_path:  /page/:num
encoding:       UTF-8
relative_permalinks:  false
permalink:      /:year/:month/:title.html
timezone:       Asia/Ho_Chi_Minh

# Custom variables
github:
  user:              programer.tips
  repos:             https://github.com/nghuuphuoc/programer.tips
google_analytics:    UA-44786951-3
google_verification: TiRE8NGZL_B2PzBSrTdfmHMs34Zvvt3sqaWU-Orm2gc
disqus:              programertips
twitter:             programertips